# ai/report_generator.py
# Author         : HuntForge Agent
# Responsibility : Generates the final bug bounty report using OpenRouter API.
# ------------------------------------------------------------

import os
import json
from loguru import logger

from ai.openrouter_helper import OpenRouterHelper


SYSTEM_PROMPT = """\
You are HuntForge AI, a senior offensive security analyst.

Write a professional executive summary and vulnerability report in Markdown format.
Structure your report with these sections:
1. Executive Summary (2-3 paragraphs)
2. Critical Findings (table format: Finding | Severity | Evidence)
3. Technology Stack Overview
4. Attack Surface Analysis
5. Recommendations (prioritized list)

Be concise, factual, and actionable. Do not fabricate findings — only report
what the provided tags and intelligence confirm.
"""


class ReportGenerator:
    def __init__(self, model: str = None):
        self.helper = OpenRouterHelper(model=model)

    def generate(self, domain: str, tag_manager, output_dir: str):
        """
        Generate an executive AI report from scan tags using OpenRouter.

        Args:
            domain:      Target domain that was scanned.
            tag_manager: TagManager instance with discovered intelligence.
            output_dir:  Path to the domain's output directory.
        """
        # Check if OpenRouter is reachable (API key is set)
        if not self.helper.is_available():
            logger.error(
                "OpenRouter API key is not set. Make sure to set OPENROUTER_API_KEY. "
                "Skipping AI report generation."
            )
            return

        logger.info(f"Generating final AI report for {domain} via OpenRouter ({self.helper.model})...")

        # ── Build context from tags ──────────────────────────────
        tags = tag_manager.get_all()

        context = f"Target Domain: {domain}\n\nDiscovered Intelligence Tags:\n"
        for tag_name, data in tags.items():
            confidence = data.get('confidence', 'unknown')
            source = data.get('source', 'unknown')
            context += f"  - {tag_name}  (confidence: {confidence}, source: {source})\n"

        # ── Add raw file stats if available ──────────────────────
        processed_dir = os.path.join(output_dir, 'processed')
        if os.path.isdir(processed_dir):
            context += "\nProcessed Data Files:\n"
            for fname in os.listdir(processed_dir):
                fpath = os.path.join(processed_dir, fname)
                if os.path.isfile(fpath):
                    size_kb = os.path.getsize(fpath) / 1024
                    context += f"  - {fname} ({size_kb:.1f} KB)\n"

        # ── Sample key raw output files for richer context ────────
        raw_dir = os.path.join(output_dir, 'raw')
        key_files = ['nuclei.json', 'dalfox.txt', 'subjack.txt', 'ffuf.json', 'httpx.json']
        if os.path.isdir(raw_dir):
            for fname in key_files:
                fpath = os.path.join(raw_dir, fname)
                if os.path.isfile(fpath) and os.path.getsize(fpath) > 0:
                    try:
                        with open(fpath, 'r', encoding='utf-8', errors='ignore') as rf:
                            lines = rf.readlines()[:30]
                        sample = ''.join(lines)[:2000]  # Cap at 2000 chars
                        context += f"\n--- Sample from {fname} ---\n{sample}\n"
                    except Exception:
                        pass

        # ── Call OpenRouter ──────────────────────────────────────────
        prompt = (
            f"Generate a professional bug bounty reconnaissance report "
            f"for the target '{domain}' based on the following intelligence:\n\n"
            f"{context}"
        )

        try:
            report_text = self.helper.generate(prompt=prompt, system=SYSTEM_PROMPT)

            # Ensure the logs directory exists
            logs_dir = os.path.join(output_dir, 'logs')
            os.makedirs(logs_dir, exist_ok=True)
            report_path = os.path.join(logs_dir, 'ai_report.md')

            with open(report_path, 'w') as f:
                f.write(f"# HuntForge AI Report — {domain}\n")
                f.write(f"_Generated by OpenRouter ({self.helper.model})_\n\n")
                f.write(report_text)

            logger.success(f"AI Report written to {report_path}")

        except Exception as e:
            logger.error(f"Failed to generate report via OpenRouter: {e}")


# CLI wrapper
def generate_report(domain, tag_manager, output_dir):
    bot = ReportGenerator()
    bot.generate(domain, tag_manager, output_dir)
